import type { Metadata } from "next";
import { Roboto_Condensed, Lobster_Two } from "next/font/google";
import "./globals.css";

const LobsterTwo = Lobster_Two({
  weight: "400",
  variable: "--font-lobster-two",
  subsets: ["latin"],
});
const geistSans = Roboto_Condensed({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Condensed({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${LobsterTwo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
